// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project below for full license information.
// https://github.com/microsoft/vstest?tab=MIT-1-ov-file

using System;

namespace Microsoft.VisualStudio.TestPlatform
{
	/// <summary>
	/// Only to be used to Test platform, to exclude auto generated code from CodeCoverage
	/// </summary>
	[AttributeUsage(AttributeTargets.All)]
	public class TestSDKAutoGeneratedCode : Attribute
	{
	}
}
